name: C/C++ code formatter (clang-format)
description: Apply clang-format to code
author: bright-tools
branding:
  icon: alert-circle
  color: green
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.clangversion }}
inputs:
  clangversion:
    description: 'Clang version'
    required: false
    default: '12'
